In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.10.0+cu128
True
Tesla T4


In [2]:
torch.empty(5, 3)

tensor([[2.6541e-20, 4.5454e-41, 2.6902e-20],
        [4.5454e-41, 1.6343e-38, 0.0000e+00],
        [2.6544e-20, 4.5454e-41, 2.6548e-20],
        [4.5454e-41, 1.5086e-38, 0.0000e+00],
        [2.6541e-20, 4.5454e-41, 1.5086e-38]])

In [4]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
torch.ones(5, 3, dtype=torch.long)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [6]:
torch.rand(5, 3)

tensor([[0.5900, 0.4160, 0.9475],
        [0.4052, 0.4053, 0.9746],
        [0.3578, 0.2935, 0.5989],
        [0.4141, 0.8278, 0.8828],
        [0.8984, 0.8368, 0.8971]])

In [9]:
torch.manual_seed(1)
torch.rand(5, 3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]])

In [10]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [12]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [13]:
torch.linspace(1, 10, 5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.full((3,3),(5))

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [16]:
torch.logspace(1,10,4)

tensor([1.0000e+01, 1.0000e+04, 1.0000e+07, 1.0000e+10])

In [45]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [18]:
x.shape

torch.Size([1])

In [20]:
torch.empty_like(x)

tensor([1009399504])

In [22]:
x.dtype

torch.int64

In [48]:
y=torch.tensor([[1,2,3],[4,5,6]])

In [49]:
y.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [30]:
#scalars and element wise with 2 tensors
# add , aub , milti , div , int div // , mod , power

<function Tensor.to_dense>

In [34]:
#random
torch.abs(y)
torch.neg(y)
torch.round(y)
torch.ceil(y)
torch.floor(y)
torch.clamp(y, min=1, max=5)
torch.sum(y)
torch.sum (y, dim=0)
torch.sum (y, dim=1)
torch.prod(y)
torch.prod(y, dim=0)
torch.prod(y, dim=1)
torch.mean(y)
torch.mean(y, dim=0)
torch.mean(y, dim=1)
torch.median(y)
torch.median(y, dim=0)
torch.median(y, dim=1)
torch.mode(y)
torch.mode(y, dim=0)
torch.mode(y, dim=1)
torch.std(y)
torch.std(y, dim=0)
torch.std(y, dim=1)
torch.var(y)
torch.var(y, dim=0)
torch.var(y, dim=1)
torch.max(y)
torch.max(y, dim=0)
torch.max(y, dim=1)
torch.min(y)
torch.min(y, dim=0)
torch.min(y, dim=1)
torch.argmax(y)
torch.argmax(y, dim=0)
torch.argmax(y, dim=1)
torch.argmin(y)
torch.argmin(y, dim=0)
torch.argmin(y, dim=1)


tensor([ 6., 15.])

In [51]:
#matrix
z=torch.tensor([[1,2],[4,5],[7,8]])
torch.mm(y,z)
torch.matmul(y,z)
torch.dot(y[0],x[0])
torch.transpose(y,0,1)
torch.det(y)
torch.inverse(y)
#torch.pinverse(y)
#torch.linalg.inv(y)
#torch.linalg.det(y)
#torch.eig(y)
#torch.svd(y)

tensor(14)

In [52]:
#compare ,>,<,==,=>,=<,!=
x>y

tensor([[False, False, False],
        [False, False, False]])

In [57]:
torch.exp(y)
torch.log(y)
torch.sqrt(y)
torch.rsqrt(y)
torch.sigmoid(y)
#torch.softmax(y, dim=0)
#torch.softmax(y, dim=1)
torch.relu(y)
torch.tanh(y)
torch.sort(y)
torch.sort(y, dim=0)
torch.sort(y, dim=1)

torch.return_types.sort(
values=tensor([[1, 2, 3],
        [4, 5, 6]]),
indices=tensor([[0, 1, 2],
        [0, 1, 2]]))

In [59]:
#inplace
#m.add_(n) now m= m+n
#m.relu_() now m= torch.relu(m)


In [60]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=a.clone

In [61]:
id(a)

139311191736096

In [62]:
id(b)

139311191735200

In [63]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [64]:
torch.tensor([1,2,3], device=device)

tensor([1, 2, 3], device='cuda:0')

In [68]:
w=torch.tensor([1,2,3])

In [67]:
e=w.to(device)

reshape

In [72]:
r=torch.tensor([[1,2,3,7],[4,5,6,8]])

In [73]:
r.reshape(2,2,2)

tensor([[[1, 2],
         [3, 7]],

        [[4, 5],
         [6, 8]]])

In [75]:
r.flatten()

tensor([1, 2, 3, 7, 4, 5, 6, 8])

In [77]:
r.permute(1,0)

tensor([[1, 4],
        [2, 5],
        [3, 6],
        [7, 8]])

In [ ]:
#unsqueeze to add an dimension and squeeze for viceverse

In [ ]:
#b = a.numpy() to change ten to num and torch.from_numpy(c)